//! Built-in rule table covering 100+ commands across file ops, git, build/test
//! tooling, package managers, and infrastructure CLIs. Each [`RuleDef`] can
//! match multiple `program` / `program:subcommand` keys; the total number of
//! distinct keys below is the "commands covered" count.
//!
//! Rules for high-traffic commands (git, cargo, npm/yarn, pytest, jest,
//! docker, kubectl, terraform) carry hand-tuned `drop`/`keep`/`group`
//! patterns. The long tail relies on the generic dedupe+truncate pipeline
//! (empty `drop`/`group`) but is still named here so lookups resolve to a
//! specific, tunable rule instead of silently falling back to `"generic"`.

use crate::rules::RuleDef;

pub static DEFAULT_RULES: &[RuleDef] = &[
    // ---------------------------------------------------------------- git
    RuleDef {
        name: "git::status",
        matches: &["git:status"],
        drop: &[r#"^\s*\(use "git [a-z ]+".*\)$"#, r"^\s*$"],
        keep: &[
            r"^\s*(modified|deleted|new file|renamed|added):",
            r"^Untracked files:",
            r"^Changes (not staged|to be committed)",
        ],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "git::diff",
        matches: &["git:diff", "git:show"],
        drop: &[r"^index [0-9a-f]+\.\.[0-9a-f]+"],
        keep: &[r"^diff --git", r"^\+\+\+", r"^---", r"^@@"],
        group: &[],
        max_lines: Some(300),
        head_lines: Some(150),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "git::log",
        matches: &["git:log", "git:reflog", "git:blame"],
        drop: &[],
        keep: &[r"^commit [0-9a-f]{7,40}"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(150),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "git::push_pull",
        matches: &["git:push", "git:pull", "git:fetch"],
        drop: &[
            r"^remote: Compressing objects",
            r"^remote: Enumerating objects",
            r"^remote: Counting objects",
            r"^Receiving objects",
            r"^Resolving deltas",
        ],
        keep: &[r"^\s*[0-9a-f]+\.\.[0-9a-f]+", r"(?i)rejected", r"(?i)error"],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "git::clone",
        matches: &["git:clone"],
        drop: &[
            r"^Cloning into",
            r"^remote: Compressing objects",
            r"^remote: Enumerating objects",
            r"^remote: Counting objects",
            r"^Receiving objects",
            r"^Resolving deltas",
        ],
        keep: &[r"(?i)error", r"(?i)fatal"],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "git::misc",
        matches: &[
            "git:add",
            "git:commit",
            "git:branch",
            "git:checkout",
            "git:switch",
            "git:stash",
            "git:remote",
            "git:tag",
            "git:merge",
            "git:rebase",
            "git:restore",
            "git:*",
        ],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    // ------------------------------------------------------------- cargo
    RuleDef {
        name: "cargo::build",
        matches: &["cargo:build", "cargo:check", "cargo:run", "cargo:bench"],
        drop: &[r"^\s*$"],
        keep: &[
            r"(?i)^error",
            r"(?i)^warning: unused",
            r"^\s*-->",
            r"(?i)panicked at",
        ],
        group: &[
            (r"^\s*Compiling \S+ v[\d.]+", "Compiling {n} crates"),
            (r"^\s*Downloaded \S+ v[\d.]+", "Downloaded {n} crates"),
            (r"^\s*Downloading \S+ v[\d.]+", "Downloading {n} crates"),
        ],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(60),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "cargo::test",
        matches: &["cargo:test"],
        drop: &[r"^\s*$", r"^running \d+ tests?$"],
        keep: &[
            r"\.\.\. FAILED$",
            r"(?i)^error",
            r"(?i)panicked at",
            r"^failures:$",
        ],
        group: &[
            (r"^test .* \.\.\. ok$", "{n} tests passed"),
            (r"^test .* \.\.\. ignored$", "{n} tests ignored"),
        ],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "cargo::clippy",
        matches: &["cargo:clippy"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)^warning", r"(?i)^error", r"^\s*-->"],
        group: &[(r"^\s*Compiling \S+ v[\d.]+", "Compiling {n} crates")],
        max_lines: Some(200),
        head_lines: Some(20),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "cargo::misc",
        matches: &[
            "cargo:fmt",
            "cargo:doc",
            "cargo:install",
            "cargo:add",
            "cargo:update",
            "cargo:tree",
            "cargo:publish",
            "cargo:fix",
            "cargo:vendor",
            "cargo:audit",
            "cargo:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)^error"],
        group: &[(r"^\s*Compiling \S+ v[\d.]+", "Compiling {n} crates")],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    // -------------------------------------------------------------- node
    RuleDef {
        name: "npm::install",
        matches: &[
            "npm:install",
            "npm:ci",
            "npm:i",
            "yarn:install",
            "yarn:*",
            "pnpm:install",
            "pnpm:i",
        ],
        drop: &[
            r"^npm warn deprecated",
            r"^npm WARN deprecated",
            r"(?i)^info fetch",
            r"^\s*$",
        ],
        keep: &[r"(?i)error", r"(?i)vulnerabilit"],
        group: &[(r"(?i)^added \d+ packages?", "package install summary")],
        max_lines: Some(120),
        head_lines: Some(20),
        tail_lines: Some(40),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "npm::run",
        matches: &["npm:run", "npm:test", "npm:start", "npm:build", "npx:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error", r"(?i)fail"],
        group: &[],
        max_lines: Some(200),
        head_lines: Some(40),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "npm::audit",
        matches: &["npm:audit", "npm:outdated", "npm:list", "npm:ls"],
        drop: &[r"^\s*$"],
        keep: &[],
        group: &[],
        max_lines: Some(100),
        head_lines: Some(50),
        tail_lines: Some(50),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "jest",
        matches: &["jest:*", "vitest:*", "mocha:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)^fail", r"✓.*$", r"(?i)expect"],
        group: &[(r"^\s*✓ ", "{n} tests passed")],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "playwright",
        matches: &["playwright:test", "playwright:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)failed", r"(?i)error"],
        group: &[(r"^\s*✓ ", "{n} tests passed")],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "eslint",
        matches: &["eslint:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error", r"(?i)warning"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(150),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "js_build_tools",
        matches: &[
            "tsc:*",
            "webpack:*",
            "vite:build",
            "vite:*",
            "next:build",
            "rollup:*",
            "esbuild:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(30),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    // ------------------------------------------------------------ python
    RuleDef {
        name: "pytest",
        matches: &["pytest:*", "py.test:*"],
        drop: &[r"^\s*$", r"^=+ warnings summary =+$"],
        keep: &[
            r"^FAILED",
            r"(?i)^error",
            r"^=+ short test summary",
            r"^E\s",
        ],
        group: &[(r"^\.+$", "{n} tests passed (dots)")],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "pip",
        matches: &[
            "pip:install",
            "pip:list",
            "pip:freeze",
            "pip:*",
            "pip3:*",
            "poetry:*",
            "uv:*",
        ],
        drop: &[r"^Requirement already satisfied", r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[(r"^Collecting \S+", "Collecting {n} packages")],
        max_lines: Some(120),
        head_lines: Some(20),
        tail_lines: Some(40),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "python_lint",
        matches: &[
            "black:*", "ruff:*", "mypy:*", "flake8:*", "tox:*", "pylint:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(150),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    // ----------------------------------------------------------------- go
    RuleDef {
        name: "go::test",
        matches: &["go:test"],
        drop: &[r"^\s*$"],
        keep: &[r"^--- FAIL", r"(?i)^error", r"^FAIL\s"],
        group: &[(r"^--- PASS", "{n} tests passed")],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "go::misc",
        matches: &["go:build", "go:vet", "go:run", "go:mod", "go:get", "go:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    // ----------------------------------------------------------- jvm/mvn
    RuleDef {
        name: "maven",
        matches: &["mvn:*"],
        drop: &[r"^\[INFO\] Download(ing|ed)", r"^\[INFO\] -+$", r"^\s*$"],
        keep: &[r"^\[ERROR\]", r"^\[WARNING\]", r"BUILD (SUCCESS|FAILURE)"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "gradle",
        matches: &["gradle:*", "gradlew:*"],
        drop: &[r"^\s*$", r"^<-+ .* -+>$"],
        keep: &[r"(?i)FAILED", r"(?i)error"],
        group: &[(r"^Task :", "{n} tasks run")],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    // --------------------------------------------------------------- make
    RuleDef {
        name: "make",
        matches: &["make:*", "cmake:*", "ninja:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error", r"(?i)undefined reference"],
        group: &[(r"^\[\s*\d+%\]", "{n} build steps")],
        max_lines: Some(150),
        head_lines: Some(30),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "compilers",
        matches: &["rustc:*", "gcc:*", "clang:*", "g++:*", "cc:*"],
        drop: &[],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(150),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    // ------------------------------------------------------------- docker
    RuleDef {
        name: "docker::build",
        matches: &["docker:build", "docker-compose:build"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error", r"^ERROR"],
        group: &[
            (r"^Step \d+/\d+", "{n} build steps"),
            (r"^#\d+ ", "{n} buildkit steps"),
        ],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "docker::ps_images",
        matches: &[
            "docker:ps",
            "docker:images",
            "docker:volume",
            "docker:network",
        ],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(60),
        head_lines: Some(60),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "docker::logs",
        matches: &["docker:logs", "docker-compose:logs", "docker:exec"],
        drop: &[],
        keep: &[r"(?i)error", r"(?i)exception", r"(?i)fatal"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(100),
        dedupe_min_repeats: Some(3),
    },
    RuleDef {
        name: "docker::misc",
        matches: &[
            "docker:run",
            "docker:inspect",
            "docker:pull",
            "docker:push",
            "docker:*",
            "docker-compose:up",
            "docker-compose:down",
            "docker-compose:*",
            "podman:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(50),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    // ------------------------------------------------------------ kubectl
    RuleDef {
        name: "kubectl::get",
        matches: &["kubectl:get", "kubectl:describe", "k9s:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(100),
        head_lines: Some(100),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "kubectl::logs",
        matches: &["kubectl:logs", "kubectl:exec"],
        drop: &[],
        keep: &[
            r"(?i)error",
            r"(?i)exception",
            r"(?i)fatal",
            r"(?i)crashloopbackoff",
        ],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(100),
        dedupe_min_repeats: Some(3),
    },
    RuleDef {
        name: "kubectl::misc",
        matches: &[
            "kubectl:apply",
            "kubectl:delete",
            "kubectl:create",
            "kubectl:rollout",
            "kubectl:*",
            "helm:*",
        ],
        drop: &[],
        keep: &[r"(?i)error"],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    // ---------------------------------------------------------------- iac
    RuleDef {
        name: "terraform",
        matches: &[
            "terraform:plan",
            "terraform:apply",
            "terraform:destroy",
            "terraform:*",
            "tofu:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error", r"^\s*[+~-] "],
        group: &[(r"^\s*# \S+ will be", "{n} resources planned")],
        max_lines: Some(200),
        head_lines: Some(30),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "pulumi",
        matches: &["pulumi:up", "pulumi:preview", "pulumi:destroy", "pulumi:*"],
        drop: &[r"^\s*$"],
        keep: &[r"(?i)error"],
        group: &[(r"^\s*\+ ", "{n} resources to create")],
        max_lines: Some(200),
        head_lines: Some(30),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "ansible",
        matches: &["ansible:*", "ansible-playbook:*"],
        drop: &[],
        keep: &[r"(?i)failed", r"(?i)error"],
        group: &[
            (r"^ok: ", "{n} tasks ok"),
            (r"^changed: ", "{n} tasks changed"),
        ],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(80),
        dedupe_min_repeats: None,
    },
    // ----------------------------------------------------------- cloud CLIs
    RuleDef {
        name: "aws_cli",
        matches: &["aws:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(75),
        tail_lines: Some(75),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "gcloud",
        matches: &["gcloud:*", "gsutil:*", "bq:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(75),
        tail_lines: Some(75),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "azure_cli",
        matches: &["az:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(75),
        tail_lines: Some(75),
        dedupe_min_repeats: None,
    },
    // ------------------------------------------------------------ file ops
    RuleDef {
        name: "fileops::listing",
        matches: &["ls:*", "ls", "tree:*", "tree", "find:*", "find"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(150),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "fileops::search",
        matches: &["grep:*", "grep", "rg:*", "rg", "ag:*", "ack:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(200),
        head_lines: Some(100),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "fileops::read",
        matches: &[
            "cat:*", "cat", "head:*", "tail:*", "wc:*", "stat:*", "file:*",
        ],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(200),
        head_lines: Some(100),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "fileops::diskspace",
        matches: &["du:*", "du", "df:*", "df"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(100),
        head_lines: Some(50),
        tail_lines: Some(50),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "fileops::mutate",
        matches: &[
            "mkdir:*", "rm:*", "cp:*", "mv:*", "chmod:*", "chown:*", "touch:*", "ln:*",
        ],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: None,
        head_lines: None,
        tail_lines: None,
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "diff_tool",
        matches: &["diff:*", "diff"],
        drop: &[],
        keep: &[r"^[<>]"],
        group: &[],
        max_lines: Some(200),
        head_lines: Some(100),
        tail_lines: Some(100),
        dedupe_min_repeats: None,
    },
    // ---------------------------------------------------------------- sys
    RuleDef {
        name: "process_list",
        matches: &["ps:*", "ps", "top:*", "htop:*"],
        drop: &[],
        keep: &[],
        group: &[],
        max_lines: Some(80),
        head_lines: Some(80),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "systemd",
        matches: &["systemctl:*", "journalctl:*"],
        drop: &[],
        keep: &[r"(?i)error", r"(?i)failed"],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(20),
        tail_lines: Some(100),
        dedupe_min_repeats: Some(3),
    },
    RuleDef {
        name: "networking",
        matches: &[
            "curl:*",
            "wget:*",
            "netstat:*",
            "ping:*",
            "dig:*",
            "nslookup:*",
            "ss:*",
        ],
        drop: &[r"^\s*$"],
        keep: &[],
        group: &[],
        max_lines: Some(150),
        head_lines: Some(75),
        tail_lines: Some(75),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "pkg_managers",
        matches: &[
            "brew:*",
            "apt:*",
            "apt-get:*",
            "yum:*",
            "dnf:*",
            "pacman:*",
            "choco:*",
            "winget:*",
            "snap:*",
        ],
        drop: &[
            r"^\s*$",
            r"^Reading package lists",
            r"^Building dependency tree",
        ],
        keep: &[r"(?i)error"],
        group: &[(r"^Get:\d+ ", "{n} packages fetched")],
        max_lines: Some(120),
        head_lines: Some(20),
        tail_lines: Some(40),
        dedupe_min_repeats: None,
    },
    RuleDef {
        name: "rustup",
        matches: &["rustup:*"],
        drop: &[r"^\s*$"],
        keep: &[],
        group: &[],
        max_lines: Some(80),
        head_lines: Some(80),
        tail_lines: Some(0),
        dedupe_min_repeats: None,
    },
];
